### ISSUE TITLE
Training code for CIFAR

### ISSUE THREAD

**Issue by error030** [LeapLabTHU/ProCo#1]
Hi, I tried to reproduce the results on the cifar dataset, but I did not reproduce the results well with the parameters set in the article. I think it's because the technical details are implemented differently. Can you please release the training code for CIFAR dataset?
Thank you：）.

**Comment by Andy-Du20** [comment]
Thanks for your interest in our work and for taking the time to provide feedback.  We have uploaded the CIFAR training code to our repository. Please feel free to reach out if you have any further questions.

**Comment by Mojtabamsd** [comment]
Hi, I have encountered the same problem for reproducing the results reported in your paper. For instance, when running several times the following command:
bash sh/ProCo_CIFAR.sh cifar100 0.01 200  


I achieved an accuracy of 51.6%, compared to the reported 52.8%. 

I used the same default parameters for running command, is there anything else I should do to replicate your results?
